main: Main.cs Object.cs ObjectSet.cs
	mcs Main.cs Object.cs ObjectSet.cs

objtest: testing/ObjTest.cs testing/TestRunner.cs old/Obj.cs old/IObj.cs
	mcs testing/ObjTest.cs testing/TestRunner.cs old/Obj.cs old/IObj.cs
