main: Main.cs Object.cs ObjectSet.cs Requirement.cs Effect.cs Player.cs Action.cs
	mcs Main.cs Object.cs ObjectSet.cs Requirement.cs Effect.cs Player.cs Action.cs

objtest: testing/ObjTest.cs testing/TestRunner.cs old/Obj.cs old/IObj.cs
	mcs testing/ObjTest.cs testing/TestRunner.cs old/Obj.cs old/IObj.cs
